//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۱۳۶۰ - شروع به فعالیت.
        /// </summary>
        public static string H1360Head {
            get {
                return ResourceManager.GetString("H1360Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت کیمیارازی در اواخر سال ۱۳۶۰ در شهر صنعتی البرز تأسیس شد..
        /// </summary>
        public static string H1360text {
            get {
                return ResourceManager.GetString("H1360text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۱۳۷۸ – نصب و بهره برداری از اولین کوره مداوم.
        /// </summary>
        public static string H1378Head {
            get {
                return ResourceManager.GetString("H1378Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به منظور ارتقاء و حفظ ثبات کیفیت محصول، کیمیارازی شروع به استفاده از آخرین فناوری روز دنیا در قالب کوره‌های مداوم نمود..
        /// </summary>
        public static string H1378Text {
            get {
                return ResourceManager.GetString("H1378Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۱۳۸۱ - توسعه واحد تولید پودر چاپ.
        /// </summary>
        public static string H1381Head {
            get {
                return ResourceManager.GetString("H1381Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هر چند پودر چاپ از بدو تأسیس شرکت کیمیارازی در سبد محصولات این شرکت بوده است، ولی در جهت افزایش کیفیت این محصول از سال ۱۳۸۱ دستگاه خشک‌کن مخصوص (Gate Dryer) راه‌اندازی گردید..
        /// </summary>
        public static string H1381Text {
            get {
                return ResourceManager.GetString("H1381Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۱۳۸۲ - واحد فرآوری مواد اولیه.
        /// </summary>
        public static string H1382Head {
            get {
                return ResourceManager.GetString("H1382Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راه‌اندازی فرآوری مواد اولیه معدنی به منظور اطمینان از ثبات کیفیت مواد اولیه مصرفی در تولید محصولات..
        /// </summary>
        public static string H1382Text {
            get {
                return ResourceManager.GetString("H1382Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۱۳۸۳ – تولید پودر چاپ لوستر.
        /// </summary>
        public static string H1383Head {
            get {
                return ResourceManager.GetString("H1383Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به منظور پاسخ گویی به نیاز مشتریان، انواع پودر چاپ لوستر به سبد محصولات شرکت کیمیارازی اضافه شد..
        /// </summary>
        public static string H1383Text {
            get {
                return ResourceManager.GetString("H1383Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۱۳۸۴ - واحد تولید دانه شکری (وتروزا).
        /// </summary>
        public static string H1384Head {
            get {
                return ResourceManager.GetString("H1384Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راه‌اندازی خط تولید انواع دانه شکری (وتروزا) با استفاده از آخرین تجهیزات و فناوری روز..
        /// </summary>
        public static string H1384Text {
            get {
                return ResourceManager.GetString("H1384Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۱۳۹۲ - تولید جوهر چاپ دیجیتال.
        /// </summary>
        public static string H1392Head {
            get {
                return ResourceManager.GetString("H1392Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راه‌اندازی چرخه کامل تولید و آزمایشگاه جوهر چاپ دیجیتال و معرفی کیمیارازی به عنوان اولین تولید کننده این محصول در ایران..
        /// </summary>
        public static string H1392Text {
            get {
                return ResourceManager.GetString("H1392Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۱۳۹۴ - تولید اکسید روی.
        /// </summary>
        public static string H1394Head {
            get {
                return ResourceManager.GetString("H1394Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راه اندازی خط تولید اکسید روی به عنوان یکی از مواد اصلی و تأثیرگذار بر کیفیت محصولات..
        /// </summary>
        public static string H1394Text {
            get {
                return ResourceManager.GetString("H1394Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه کیمیارازی.
        /// </summary>
        public static string HistoryHead {
            get {
                return ResourceManager.GetString("HistoryHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه مختصری از شرکت کیمیارازی.
        /// </summary>
        public static string HistorySubhead {
            get {
                return ResourceManager.GetString("HistorySubhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت کیمیارازی در اواخر سال ۱۳۶۰ در شهر صنعتی البرز قزوین تأسیس شد. کیمیارازی در حال حاضر در دو مجموعه مستقل و در زمینی به مساحت حدود ۱۸ هکتار و دفتر مرکزی مستقر در تهران به عنوان بزرگترین و اصلی‌ترین تولید کننده لعاب کشور مشغول به تولید و فعالیت می‌باشد. فعالیت شرکت با تولید ۴۰۰۰ تن محصول در سال شروع شده و در حال حاضر به حداقل ۸۰۰۰۰ تن در سال رسیده است. با توجه به سیاست سهامداران آن مبنی بر به روز بودن و رشد شرکت، کیمیارازی طی مراحل زیر فعالیت خود را گسترش داده است:.
        /// </summary>
        public static string HistoryText {
            get {
                return ResourceManager.GetString("HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه کیمیارازی.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برآورده نمودن الزامات و خواسته‌های مشتریان از طریق تولید محصول با کیفیت و منطبق با نیازها، انتظارات و توافقات مشتریان و درک صحیح آنها..
        /// </summary>
        public static string PolicyList1 {
            get {
                return ResourceManager.GetString("PolicyList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گسترش فعالیت تحقیق و توسعه با توجه به امکانات شرکت در جهت تقویت توان رقابتی شرکت، حضور فعال و موفق در بازار، دست‌یابی به راه‌کارهای تولید اقتصادی و به‌کارگیری دانش و فناوری نوین..
        /// </summary>
        public static string PolicyList2 {
            get {
                return ResourceManager.GetString("PolicyList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بهسازی منابع انسانی به عنوان با ارزش‌ترین سرمایه شرکت از طریق مشارکت فعال آنان در فعالیت‌ها و آموزش مستمر ایشان و استخدام نیروهای متخصص و مجرب..
        /// </summary>
        public static string PolicyList3 {
            get {
                return ResourceManager.GetString("PolicyList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط مؤثر با تأمین کنندگان مواد اولیه در جهت تأمین به موقع و با کیفیت تعیین شده مواد اولیه مصرفی شرکت..
        /// </summary>
        public static string PolicyList4 {
            get {
                return ResourceManager.GetString("PolicyList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت کیمیارازی اولین و بزرگ‌ترین تولیدکننده لعاب کاشی و سرامیک و جوهر چاپ دیجیتال در ایران می‌باشد که در راستای تعهد به تأمین نیازها، انتظارات و رضایت مشتریان با بهره‌گیری از فناوری نوین و نیروی متخصص و مجرب، محصولات خود را ارتقاء کیفیت داده و خود را متعهد به بهبود مستمر فرآیندها با توجه به قابلیت و توانایی‌های شرکت می‌داند و در این راستا تعهد خود را که چهارچوبی برای تعیین اهداف کیفی شرکت هستند به عنوان رئوس خط مشی شرکت اعلام می‌دارد:.
        /// </summary>
        public static string PolicyText {
            get {
                return ResourceManager.GetString("PolicyText", resourceCulture);
            }
        }
    }
}
