//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Contact {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contact() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.Contact", typeof(Contact).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تهران – میدان ونک – خیابان ملاصدرا – خیابان شیراز جنوبی – نبش کوچه سرو – پلاک ۳۱ – طبقه چهارم - کد پستی: ۱۴۳۵۸۸۳۱۳۴&lt;br /&gt;
        ///                    تلفن: ۲ – ۸۸۰۴۱۴۵۰ (۰۲۱)&lt;br /&gt;فکس: ۸۸۰۴۱۴۵۳ (۰۲۱).
        /// </summary>
        public static string Address1Text {
            get {
                return ResourceManager.GetString("Address1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفتر مرکزی.
        /// </summary>
        public static string Address1Title {
            get {
                return ResourceManager.GetString("Address1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قزوین - شهر صنعتی البرز - فلکه دوم - خیابان میرداماد غربی - جنب اداره پست - خیابان فارابی جنوبی &lt;br /&gt;
        ///                    تلفن: ۳۲۲۲۲۶۵۸ – ۳۲۲۲۳۶۵۸ (۰۲۸)&lt;br /&gt;فکس: ۳۲۲۲۲۵۵۱ (۰۲۸).
        /// </summary>
        public static string Address2Text {
            get {
                return ResourceManager.GetString("Address2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارخانه (واحد ۱).
        /// </summary>
        public static string Address2Title {
            get {
                return ResourceManager.GetString("Address2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیلومتر ۱۵ جاده بوئین زهرا - قزوین - شهر صنعتی برلیان - خیابان پاکنام - جنب شرکت برلیان تهران&lt;br /&gt;
        ///                    تلفن: ۳۶۳۳۲۳۳۱ (۰۲۸).
        /// </summary>
        public static string Address3Text {
            get {
                return ResourceManager.GetString("Address3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارخانه (واحد ۲).
        /// </summary>
        public static string Address3Title {
            get {
                return ResourceManager.GetString("Address3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً یک آدرس ایمیل معتبر جهت تماس وارد فرمایید..
        /// </summary>
        public static string ErrorEmptyMsgMail {
            get {
                return ResourceManager.GetString("ErrorEmptyMsgMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً نام خود را وارد کنید..
        /// </summary>
        public static string ErrorEmptyMsgName {
            get {
                return ResourceManager.GetString("ErrorEmptyMsgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن پیام نباید خالی باشد..
        /// </summary>
        public static string ErrorEmptyMsgText {
            get {
                return ResourceManager.GetString("ErrorEmptyMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string MsgEmail {
            get {
                return ResourceManager.GetString("MsgEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام.
        /// </summary>
        public static string MsgHead {
            get {
                return ResourceManager.GetString("MsgHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string MsgName {
            get {
                return ResourceManager.GetString("MsgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string MsgPhone {
            get {
                return ResourceManager.GetString("MsgPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام.
        /// </summary>
        public static string MsgSendBtn {
            get {
                return ResourceManager.GetString("MsgSendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت تمایل پیام خود را از این قسمت برای کیمیارازی ارسال کنید..
        /// </summary>
        public static string MsgSubhead {
            get {
                return ResourceManager.GetString("MsgSubhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام شما.
        /// </summary>
        public static string MsgText {
            get {
                return ResourceManager.GetString("MsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با کیمیارازی.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت هر گونه درخواست یا پرسش با ما تماس بگیرید..
        /// </summary>
        public static string Subhead {
            get {
                return ResourceManager.GetString("Subhead", resourceCulture);
            }
        }
    }
}
