//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DigitalInk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DigitalInk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.DigitalInk", typeof(DigitalInk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بژ.
        /// </summary>
        public static string Beige {
            get {
                return ResourceManager.GetString("Beige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکی.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبی.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قهوه‌ای.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایان.
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;شرکت کیمیارازی به عنوان اولین و تنها تولید کننده جوهرهای مخصوص چاپ دیجیتال روی کاشی در ایران از سال ۱۳۹۲ بعد از نصب ماشین آلات و آماده‌سازی سالن تولید با همکاری شرکت‌های ایتالیایی شروع به تولید کرد. ما در حال حاضر با اخذ گواهی کیفیت (سرتیفیکیت) تعدادی از شرکت‌های تولید کننده ماشین‌های چاپ دیجیتال جوهر مورد نیاز شرکت‌های مختلف را با برندهای متفاوت پرینتر دیجیتال تأمین می‌کنیم. در حال حاضر جوهرهای ما از جمله در دستگاه‌های System، Intesa، Durst، Techno-Ferrari، projecta، kerajet و… مورد استفاده قرار گرفته ا [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوهر ویژه چاپ دیجیتال.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عسلی.
        /// </summary>
        public static string Honey {
            get {
                return ResourceManager.GetString("Honey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات - جوهر دیجیتال.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورتی.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای دانلود فایل مشخصات فنی جوهرها روی لینک زیر کلیک کنید.
        /// </summary>
        public static string TableDlDesc {
            get {
                return ResourceManager.GetString("TableDlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول مشخصات جوهرهای کیمیارازی.
        /// </summary>
        public static string TableLinkText {
            get {
                return ResourceManager.GetString("TableLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چرا جوهر کیمیارازی؟.
        /// </summary>
        public static string WhyHead {
            get {
                return ResourceManager.GetString("WhyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسان کیمیارازی بلافاصله آماده ارائه خدماتی نظیر شستشو و جایگزینی جوهر کیمیارازی در دستگاه، ساخت پروفایل، تطبیق طرح‌های قبلی با جوهر جدید و هر گونه مشاوره در خصوص جوهر و چاپ و طرح دیجیتال هستند..
        /// </summary>
        public static string WhyList1 {
            get {
                return ResourceManager.GetString("WhyList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوهر کیمیارازی در دستگاه‌های مختلف جایگزین جوهرهای تأمین کننده‌های مطرح اروپایی فعال در بازار ایران شده و از این طریق مقایسه بین جوهر ما و جوهرهای وارداتی انجام شده است. کیفیت و شدت رنگ‌ها کاملاْ با نمونه‌های با کیفیت بازار قابل رقابت بوده در بعضی از رنگ‌ها شید قوی‌تری نیز دارد. در این مقایسه‌ها مشخص شد که میزان مصرف این جوهر نیز مشابه جوهرهای وارداتی است..
        /// </summary>
        public static string WhyList2 {
            get {
                return ResourceManager.GetString("WhyList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت مناسب‌تر از جوهرهای وارداتی..
        /// </summary>
        public static string WhyList3 {
            get {
                return ResourceManager.GetString("WhyList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نزدیکی زمان تولید و مصرف و کاهش ریسک رسوب و توده‌ای شدن جوهر و افزایش عمر هدها..
        /// </summary>
        public static string WhyList4 {
            get {
                return ResourceManager.GetString("WhyList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم وجود مسائل گمرکی و مشکلات مربوط به واردات کالا..
        /// </summary>
        public static string WhyList5 {
            get {
                return ResourceManager.GetString("WhyList5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحویل جوهر حداکثر ۳ روز پس از سفارش به هر میزان. - به دلیل اطمینان از تحویل به موقع جوهر، نیاز به سفارش مقادیر زیاد جوهر وجود ندارد و کم بودن موجودی انبار مشتری، احتمال منقضی شدن تاریخ مصرف جوهر را به حداقل می‌رساند..
        /// </summary>
        public static string WhyList6 {
            get {
                return ResourceManager.GetString("WhyList6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حتی در صورت منقضی شدن تاریخ مصرف، امکان بازگرداندن جوهر به ابتدای فرایند تولید در کیمیارازی وجود دارد بنابراین هیچ مشکلی از نظر کارکرد دستگاه و شید رنگی طرح به وجود نخواهد آمد..
        /// </summary>
        public static string WhyList7 {
            get {
                return ResourceManager.GetString("WhyList7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با وجود زمان کمی که از شروع تولید و ارائه جوهر به بازار می‌گذرد تعداد واحدهای تولیدی که جوهر کیمیارازی را مصرف می‌کنند به سرعت در حال افزایش است..
        /// </summary>
        public static string WhyList8 {
            get {
                return ResourceManager.GetString("WhyList8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با آزمایشگاه مجهز به آخرین فناوری روز دنیا، کلیه تست‌های جوهر با دقت بسیار بالا انجام شده و هیچ گونه نگرانی در مورد کیفیت و ثبات آن وجود ندارد..
        /// </summary>
        public static string WhyList9 {
            get {
                return ResourceManager.GetString("WhyList9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زرد.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
