//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Frit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Frit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.Frit", typeof(Frit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصلی‌ترین دغدغه کیمیارازی بعد از ارائه محصول متناسب با درخواست مشتری، حفظ ثبات کیفیت و یکنواختی در محصول ارائه شده است که این مهم در مورد فریت‌ها با استفاده از چند عامل زیر محقق شده است:.
        /// </summary>
        public static string BeforeList {
            get {
                return ResourceManager.GetString("BeforeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///فریت‌ها جزء اصلی تقریباً همه لعاب‌های سرامیکی هستند و در بسیاری از ترکیباتی که سطح شیشه‌ای در آنها مورد نیاز است وجود دارند. تنوع موارد استفاده و روش‌های تولید کاشی‌هایی که فریت در آنها استفاده می‌شود، باعث شده که فریت‌ها در طول زمان تنوع کیفی زیادی پیدا کنند.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///فریت‌ها بر مبانی مختلف دارای تقسیم بندی‌های متنوعی هستند که شرکت کیمیارازی با استفاده از ماشین‌آلات مدرن و نیروی متخصص خود و با پشتوانه حدود چهار دهه تجربه تولید انواع فریت، هر نوع فریتی را تولید می‌کند. با تنوع بالای محصولات، کیمیارا [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فریت‌ها.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بهره‌گیری از نیروهای متخصص و مجرب در کلیه مراحل تولید و آزمایشگاه.
        /// </summary>
        public static string List1 {
            get {
                return ResourceManager.GetString("List1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده از مواد اولیه مرغوب جهت تولید فریت..
        /// </summary>
        public static string List2 {
            get {
                return ResourceManager.GetString("List2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده از تجهیزات مدرن آزمایشگاهی و تولیدی..
        /// </summary>
        public static string List3 {
            get {
                return ResourceManager.GetString("List3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه سفارش‌های فریت با تناژ بالا در کوره‌های مداوم تولید می‌گردد..
        /// </summary>
        public static string List4 {
            get {
                return ResourceManager.GetString("List4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنترل دقیق مواد اولیه ورودی به لحاظ ثبات با استفاده از تست‌های کمی و کیفی مقایسه‌ای و آنالیزی..
        /// </summary>
        public static string List5 {
            get {
                return ResourceManager.GetString("List5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنترل دقیق فریت تولیدی به صورت نمونه برداری و تست هر تن از فریت تولیدی..
        /// </summary>
        public static string List6 {
            get {
                return ResourceManager.GetString("List6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنترل ضریب و مشخصات پخت با استفاده از دیلاتومتر و میکروسکوپ حرارتی..
        /// </summary>
        public static string List7 {
            get {
                return ResourceManager.GetString("List7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دپوی مناسب از مواد اولیه. همیشه حداقل به اندازه یک سال تولید مواد اولیه دپو انبار می‌باشد..
        /// </summary>
        public static string List8 {
            get {
                return ResourceManager.GetString("List8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده از سیستم همگن سازی (میکس) فریت‌ها قبل از ارسال برای مشتری..
        /// </summary>
        public static string List9 {
            get {
                return ResourceManager.GetString("List9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات - فریت.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod1Feature {
            get {
                return ResourceManager.GetString("Prod1Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فریت ترانسپارنت.
        /// </summary>
        public static string Prod1H {
            get {
                return ResourceManager.GetString("Prod1H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod1Subhead {
            get {
                return ResourceManager.GetString("Prod1Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod1Text {
            get {
                return ResourceManager.GetString("Prod1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod2Feature {
            get {
                return ResourceManager.GetString("Prod2Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فریت مات.
        /// </summary>
        public static string Prod2H {
            get {
                return ResourceManager.GetString("Prod2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod2Subhead {
            get {
                return ResourceManager.GetString("Prod2Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod2Text {
            get {
                return ResourceManager.GetString("Prod2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod3Feature {
            get {
                return ResourceManager.GetString("Prod3Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فریت اوپک.
        /// </summary>
        public static string Prod3H {
            get {
                return ResourceManager.GetString("Prod3H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod3Subhead {
            get {
                return ResourceManager.GetString("Prod3Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod3Text {
            get {
                return ResourceManager.GetString("Prod3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Feature {
            get {
                return ResourceManager.GetString("Prod4Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فریت انگوب.
        /// </summary>
        public static string Prod4H {
            get {
                return ResourceManager.GetString("Prod4H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Subhead {
            get {
                return ResourceManager.GetString("Prod4Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Text {
            get {
                return ResourceManager.GetString("Prod4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما اولین و بزرگترین تولید کننده انواع فریت جهت تولید کنندگان کاشی و سرامیک در ایران هستیم. محصولات ما با ویژگی‌های متنوع از نظر نوع، ضریب انبساط حرارتی و دمای پخت سهم به سزایی در موفقیت بسیاری از تولید کنندگان مطرح کاشی و سرامیک ایران دارد..
        /// </summary>
        public static string Subhead {
            get {
                return ResourceManager.GetString("Subhead", resourceCulture);
            }
        }
    }
}
