//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Glaze {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Glaze() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.Glaze", typeof(Glaze).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توصیه کیمیارازی به مشتریان خود استفاده از مجموعه‌های آماده انگوب و لعاب می‌باشد..
        /// </summary>
        public static string Conclusion {
            get {
                return ResourceManager.GetString("Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;شرکت کیمیارازی با تکیه بر کیفیت بالای فریت‌ها و مواد اولیه در دسترس این شرکت یکی از بزرگترین تولید کنندگان مجموعه‌های لعاب و انگوب در ایران است. کارشناسان ما در صورت تمایل مشتری با توجه به شرایط تولید هر تولید کننده کاشی و سرامیک، اقدام به طراحی مجموعه‌های لعاب یا انگوب می‌نمایند. محصولات تولید شده شامل لعاب‌های مات با انواع افکت‌های سطحی ویژه این نوع لعاب، انواع انگوب با رنج وسیعی از ضریب انبساط و حرارت پخت برای کاشی دیوار، مونوپروزا، کف و پرسلان و انواع لعاب‌های ترانسپارنت و اوپک می‌باشد.&lt;/p&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه‌ها (کامپوند).
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه‌های آماده انگوب و لعاب در کیمیارازی به صورت کاملاً اتوماتیک تولید می‌شود و امکان اشتباه پرسنلی در توزین و میکس مجموعه وجود ندارد..
        /// </summary>
        public static string List1 {
            get {
                return ResourceManager.GetString("List1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با توجه به این که کیمیارازی تولیدکننده فریت است از مواد اولیه با کیفیت و تنوع بالا در تولید مجموعه لعاب و انگوب استفاده می‌کند..
        /// </summary>
        public static string List2 {
            get {
                return ResourceManager.GetString("List2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل این که کار تخصصی کارشناسان کیمیارازی فرموله کردن لعاب است، مجموعه‌های آماده انگوب و لعاب فرموله شده توسط آنها کیفیت بالاتری دارد..
        /// </summary>
        public static string List3 {
            get {
                return ResourceManager.GetString("List3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت خرید مجموعه‌های آماده، تولید کنندگان کاشی و سرامیک نیازی به دپوی انبار از مواد اولیه مختلف و متعدد جهت ساخت مجموعه‌های مصرفی نخواهند داشت..
        /// </summary>
        public static string List4 {
            get {
                return ResourceManager.GetString("List4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت بروز مشکل در مجموعه مصرفی، مسئولیت آن به عهده کیمیارازی است و مشتری تنها با یک تأمین کننده روبرو می‌شود..
        /// </summary>
        public static string List5 {
            get {
                return ResourceManager.GetString("List5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان استفاده از مشاوره‌های بیشتر کیمیارازی به ویژه در مواقع بروز مشکل وجود دارد..
        /// </summary>
        public static string List6 {
            get {
                return ResourceManager.GetString("List6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در نهایت به دلایل فوق کیفیت محصول تولیدی توسط مشتری ارتقا می‌یابد..
        /// </summary>
        public static string List7 {
            get {
                return ResourceManager.GetString("List7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات - لعاب آماده (کامپوند).
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod1Feature {
            get {
                return ResourceManager.GetString("Prod1Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه انگوب.
        /// </summary>
        public static string Prod1H {
            get {
                return ResourceManager.GetString("Prod1H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه انگوب آماده کیمیارازی.
        /// </summary>
        public static string Prod1Subhead {
            get {
                return ResourceManager.GetString("Prod1Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطبق با ویژگی‌های مورد درخواست مشتری با ضریب انبساط منتاسب با بدنه‌ها و لعاب‌های گوناگون منطبق با ویژگی‌های مورد درخواست مشتری آماده ارائه به مشتریان می‌باشد..
        /// </summary>
        public static string Prod1Text {
            get {
                return ResourceManager.GetString("Prod1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod2Feature {
            get {
                return ResourceManager.GetString("Prod2Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لعاب مات.
        /// </summary>
        public static string Prod2H {
            get {
                return ResourceManager.GetString("Prod2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه لعاب مات کیمیارازی.
        /// </summary>
        public static string Prod2Subhead {
            get {
                return ResourceManager.GetString("Prod2Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع لعاب مات ترانس و مات اوپک با سطح ابریشمی یا زبر و مقاومت شیمیایی بالا متناسب با شرایط مختلف کاری مشتری.
        /// </summary>
        public static string Prod2Text {
            get {
                return ResourceManager.GetString("Prod2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod3Feature {
            get {
                return ResourceManager.GetString("Prod3Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لعاب ترانسپارنت و اوپک.
        /// </summary>
        public static string Prod3H {
            get {
                return ResourceManager.GetString("Prod3H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه لعاب ترانسپارنت و لعاب اوپک براق کیمیارازی.
        /// </summary>
        public static string Prod3Subhead {
            get {
                return ResourceManager.GetString("Prod3Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متناسب با خواست مشتری با فریت‌ها و مواد اولیه با کیفیت آماده ارائه به مشتریان می‌باشد..
        /// </summary>
        public static string Prod3Text {
            get {
                return ResourceManager.GetString("Prod3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Feature {
            get {
                return ResourceManager.GetString("Prod4Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4H {
            get {
                return ResourceManager.GetString("Prod4H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Subhead {
            get {
                return ResourceManager.GetString("Prod4Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Text {
            get {
                return ResourceManager.GetString("Prod4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعه لعاب و انگوب آماده.
        /// </summary>
        public static string Subhead {
            get {
                return ResourceManager.GetString("Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسیاری از تولید کنندگان برتر کاشی و سرامیک در جمع مشتریان لعاب‌های ما هستند. چون….
        /// </summary>
        public static string WhyHead {
            get {
                return ResourceManager.GetString("WhyHead", resourceCulture);
            }
        }
    }
}
