//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیمیـارازی.
        /// </summary>
        public static string BigCompanyName {
            get {
                return ResourceManager.GetString("BigCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیمیارازی.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string Feature1Head {
            get {
                return ResourceManager.GetString("Feature1Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای رسیدن به بهترین محصول نهایی، ما همواره در ارتباط نزدیک با مشتریان هستیم..
        /// </summary>
        public static string Feature1text {
            get {
                return ResourceManager.GetString("Feature1text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیفیت.
        /// </summary>
        public static string Feature2Head {
            get {
                return ResourceManager.GetString("Feature2Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسیاری از بزرگ‌ترین و موفق‌ترین شرکت‌های تولیدکننده کاشی و سرامیک از محصولات ما استفاده می‌کنند..
        /// </summary>
        public static string Feature2text {
            get {
                return ResourceManager.GetString("Feature2text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فناوری.
        /// </summary>
        public static string Feature3Head {
            get {
                return ResourceManager.GetString("Feature3Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات ما با استفاده از به روزترین و پیشرفته ترین تجهیزات و ماشین‌آلات، طراحی و تولید می‌شوند..
        /// </summary>
        public static string Feature3text {
            get {
                return ResourceManager.GetString("Feature3text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجربه.
        /// </summary>
        public static string Feature4Head {
            get {
                return ResourceManager.GetString("Feature4Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با سابقه بیش از سه دهه٬ کیمیارازی قدیمی‌ترین و بزرگ‌ترین تولید کننده فریت و لعاب در ایران است..
        /// </summary>
        public static string Feature4text {
            get {
                return ResourceManager.GetString("Feature4text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;light&quot;&gt;صفحه&lt;/span&gt; اصلی.
        /// </summary>
        public static string HomeLinkText {
            get {
                return ResourceManager.GetString("HomeLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیمیارازی.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط مشی کیمیارازی.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیشتر بدانید.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;colored-span&quot;&gt;اولین&lt;/span&gt; و &lt;span class=&quot;colored-span&quot;&gt;بزرگ‌ترین&lt;/span&gt; تولید کننده انواع لعاب&lt;br&gt;و جوهر دیجیتال در ایران.
        /// </summary>
        public static string Subheading1 {
            get {
                return ResourceManager.GetString("Subheading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;colored-span&quot;&gt;گسترده‌ترین&lt;/span&gt; و &lt;span class=&quot;colored-span&quot;&gt;به‌روزترین&lt;/span&gt; سبد محصولات&lt;br&gt;در صنعت لعاب کشور.
        /// </summary>
        public static string Subheading2 {
            get {
                return ResourceManager.GetString("Subheading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Subheading3 {
            get {
                return ResourceManager.GetString("Subheading3", resourceCulture);
            }
        }
    }
}
