//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Nav {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Nav() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.Nav", typeof(Nav).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوهر.
        /// </summary>
        public static string Digitalprinting {
            get {
                return ResourceManager.GetString("Digitalprinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجه.
        /// </summary>
        public static string Feature1Scale_Degree {
            get {
                return ResourceManager.GetString("Feature1Scale_Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (در دمای ۴۰۰ درجه).
        /// </summary>
        public static string Feature2Scale_TEC {
            get {
                return ResourceManager.GetString("Feature2Scale_TEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فریت.
        /// </summary>
        public static string Frit {
            get {
                return ResourceManager.GetString("Frit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لعاب.
        /// </summary>
        public static string Glaze {
            get {
                return ResourceManager.GetString("Glaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ.
        /// </summary>
        public static string Printpowder {
            get {
                return ResourceManager.GetString("Printpowder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات محصول.
        /// </summary>
        public static string ProductDesc {
            get {
                return ResourceManager.GetString("ProductDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیشترین دمای پخت.
        /// </summary>
        public static string ProductFeature1_MaxTemp {
            get {
                return ResourceManager.GetString("ProductFeature1_MaxTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمترین دمای پخت.
        /// </summary>
        public static string ProductFeature1_MinTemp {
            get {
                return ResourceManager.GetString("ProductFeature1_MinTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیشترین ضریب انبساط.
        /// </summary>
        public static string ProductFeature2_MaxTEC {
            get {
                return ResourceManager.GetString("ProductFeature2_MaxTEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمترین ضریب انبساط.
        /// </summary>
        public static string ProductFeature2_MinTEC {
            get {
                return ResourceManager.GetString("ProductFeature2_MinTEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات فنی.
        /// </summary>
        public static string ProductSpecs {
            get {
                return ResourceManager.GetString("ProductSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string ReturnBtn {
            get {
                return ResourceManager.GetString("ReturnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لعاب‌های ویژه.
        /// </summary>
        public static string Specialglazes {
            get {
                return ResourceManager.GetString("Specialglazes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پخت سوم.
        /// </summary>
        public static string Thirdfiring {
            get {
                return ResourceManager.GetString("Thirdfiring", resourceCulture);
            }
        }
    }
}
