//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Powder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Powder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.Powder", typeof(Powder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;کیفیت پودر چاپ نقش بسیار مهمی در کیفیت طرح اعمال شده روی بدنه و عمر دستگاه‌های چاپ تخت یا روتوکالر دارد. در کنار استفاده از رنگ‌های مناسب و با کیفیت٬ برای رسیدن به کیفیت و ثبات بهینه باید مناسب‌ترین پودر چاپ به کار برده شود.&lt;/p&gt;
        ///                &lt;p&gt;پودر چاپ‌های شرکت کیمیارازی با استفاده از آخرین فناوری روز و تجهیزات پیشرفته تولید می‌شوند تا کیفیت بالا و ثبات مورد نظر مشتری تأمین گردد.&lt;/p&gt;
        ///                &lt;p&gt;تنوع بالای محصولات٬ ما را قادر می‌کند که پاسخ‌گوی هر نوع نیاز در بازار متنوع این محصول باشیم. و ک [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات - انواع پودر چاپ.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دمای پخت از ۱۰۱۰ تا ۱۱۸۰.
        /// </summary>
        public static string Prod1Feature {
            get {
                return ResourceManager.GetString("Prod1Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ ترانسپارنت.
        /// </summary>
        public static string Prod1H {
            get {
                return ResourceManager.GetString("Prod1H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ ترانسپارنت کیمیارازی.
        /// </summary>
        public static string Prod1Subhead {
            get {
                return ResourceManager.GetString("Prod1Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با رنگ‌دهی بالا و درجه‌های متنوع براقیت آماده ارایه به مشتریان با نیازهای متنوع..
        /// </summary>
        public static string Prod1Text {
            get {
                return ResourceManager.GetString("Prod1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دمای پخت از ۱۰۱۰ تا ۱۱۸۰.
        /// </summary>
        public static string Prod2Feature {
            get {
                return ResourceManager.GetString("Prod2Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ مات.
        /// </summary>
        public static string Prod2H {
            get {
                return ResourceManager.GetString("Prod2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ مات کیمیارازی.
        /// </summary>
        public static string Prod2Subhead {
            get {
                return ResourceManager.GetString("Prod2Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع پودر چاپ مات ترانس و مات اوپک با تنوع بالا در کیفیت سطح و سایر ویژگی‌های نوری. کارشناسان ما در سریعترین زمان مناسب‌ترین محصول را برای شرایط ویژه تولید شما آماده می‌کنند..
        /// </summary>
        public static string Prod2Text {
            get {
                return ResourceManager.GetString("Prod2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دمای پخت از ۱۰۱۰ تا ۱۱۸۰.
        /// </summary>
        public static string Prod3Feature {
            get {
                return ResourceManager.GetString("Prod3Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ اوپک.
        /// </summary>
        public static string Prod3H {
            get {
                return ResourceManager.GetString("Prod3H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ اوپک کیمیارازی.
        /// </summary>
        public static string Prod3Subhead {
            get {
                return ResourceManager.GetString("Prod3Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطبق با ویژگی‌های مورد درخواست مشتری با سفیدی و براقیت بالا و مناسب استفاده در طرح‌هایی که چاپ رنگ سفید در آنها استفاده شده است..
        /// </summary>
        public static string Prod3Text {
            get {
                return ResourceManager.GetString("Prod3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دمای پخت از ۹۵۰ تا ۱۲۰۰.
        /// </summary>
        public static string Prod4Feature {
            get {
                return ResourceManager.GetString("Prod4Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ ری‌اکتیو.
        /// </summary>
        public static string Prod4H {
            get {
                return ResourceManager.GetString("Prod4H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ ری اکتیو کیمیارازی.
        /// </summary>
        public static string Prod4Subhead {
            get {
                return ResourceManager.GetString("Prod4Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با قدرت نفوذ بالا جهت ایجاد فرورفتگی روی سطح لعاب در طرح‌هایی که بافت غیر هم‌سطح دارند..
        /// </summary>
        public static string Prod4Text {
            get {
                return ResourceManager.GetString("Prod4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دمای پخت از ۱۰۱۰ تا ۱۱۸۰.
        /// </summary>
        public static string Prod5Feature {
            get {
                return ResourceManager.GetString("Prod5Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ لوستر.
        /// </summary>
        public static string Prod5H {
            get {
                return ResourceManager.GetString("Prod5H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پودر چاپ لوستر کیمیارازی.
        /// </summary>
        public static string Prod5Subhead {
            get {
                return ResourceManager.GetString("Prod5Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت حصول جلای بیشتر در طرح‌ها با انعکاس نور بالا..
        /// </summary>
        public static string Prod5Text {
            get {
                return ResourceManager.GetString("Prod5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع پودر چاپ کیمیارازی.
        /// </summary>
        public static string Subhead {
            get {
                return ResourceManager.GetString("Subhead", resourceCulture);
            }
        }
    }
}
