//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Services {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Services() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.Services", typeof(Services).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;شرکت کیمیارازی برای رسیدن به بهترین راه‌های همکاری و موفقیت در پروژه‌های مورد علاقه و واجد منافع مشترک برای طرفین، همواره در ارتباط تنگاتنگ با مشتریان است. خدمات مهندسی ارائه شده به مشتریان همواره یکی از اصول مهم شرکت کیمیارازی بوده است. &lt;/p&gt;
        ///&lt;p&gt;با تکیه بر تیم حرفه‌ای و ارتباط نزدیک با مشتریان، شرکت کیمیارازی برای ارتقای سطح کیفی محصولات مشتریان، پشتیبانی فنی و انتقال دانش لازم را فراهم می کند. ما به منظور فراهم کردن بهترین راه‌حل‌ها تا رسیدن به بهترین نتایج متناسب با شرایط ویژه هر مشتری، با آنها در ارتب [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MetaDesc {
            get {
                return ResourceManager.GetString("MetaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیمیارازی - خدمات.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت کیمیارازی به شرکت‌های تولیدکننده کاشی و سرامیک در دو بخش لعاب و جوهر دیجیتال خدمات ارائه می‌کند..
        /// </summary>
        public static string Subhead {
            get {
                return ResourceManager.GetString("Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی و ساخت انواع لعاب مورد نظر شما.
        /// </summary>
        public static string Svc1h {
            get {
                return ResourceManager.GetString("Svc1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما آمادگی داریم هرگونه لعاب (فریت، مجموعه، پودر و غیره) را به‌طور اختصاصی و مناسب شرایط تولیدتان طراحی و روی خط تولید شما تست کنیم تا مناسب‌ترین فرمول ممکن برای رسیدن به محصول نهایی با کیفیت دلخواه حاصل شود..
        /// </summary>
        public static string Svc1t {
            get {
                return ResourceManager.GetString("Svc1t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارائه مشاوره درخصوص رفع مشکلات و بهبود کیفیت محصولات شرکت‌های کاشی و سرامیک.
        /// </summary>
        public static string Svc2h {
            get {
                return ResourceManager.GetString("Svc2h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأمین کیفیت بالای تولیدات مشتریان از تعهدات کیمیارازی بوده و در این راه از طریق ارائه محصولات باکیفیت و نیز همراهی و همکاری به‌منظور رفع مشکلات تولید مشتری و توصیه به تغییرات مناسب در کنار مشتریان خود خواهد بود..
        /// </summary>
        public static string Svc2t {
            get {
                return ResourceManager.GetString("Svc2t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همراهی کارشناسان ما در انجام آزمون آزمایشگاهی و صنعتی .
        /// </summary>
        public static string Svc3h {
            get {
                return ResourceManager.GetString("Svc3h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسان مجرب شرکت آماده انجام آزمون آزمایشگاهی و صنعتی لعاب‌های مورد استفاده کارخانجات کاشی هستند تا بتوانند بهترین کیفیت را به مشتریان ارائه کنند..
        /// </summary>
        public static string Svc3t {
            get {
                return ResourceManager.GetString("Svc3t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطبیق طرح‌های مورد نظر شما با جوهرهای ما.
        /// </summary>
        public static string Svc4h {
            get {
                return ResourceManager.GetString("Svc4h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشتریانی که قبلاً طرح‌هایی با جوهرهای دیگر تولید و وارد بازار کرده‌اند این امکان وجود دارد تا با کمک کارشناسان کیمیارازی طرح‌های قبلی را از نظر طرح و رنگ کاملاْ منطبق با جوهر کیمیارازی تولید کنند و هیچ نگرانی بابت انطباق رنگ نداشته باشند..
        /// </summary>
        public static string Svc4t {
            get {
                return ResourceManager.GetString("Svc4t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساخت و اصلاح پروفایل.
        /// </summary>
        public static string Svc5h {
            get {
                return ResourceManager.GetString("Svc5h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیمیارازی بنا به درخواست مشتری، با بهره‌گیری از دستگاه‌ها و نرم‌افزارهای روز دنیا قابلیت ساخت پروفایل متناسب با کلیه شرایط بدنه، انگوب، لعاب، پخت و… را در کوتاه‌ترین زمان دارد..
        /// </summary>
        public static string Svc5t {
            get {
                return ResourceManager.GetString("Svc5t", resourceCulture);
            }
        }
    }
}
