//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Services {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Services() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.Services", typeof(Services).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;شرکت کیمیارازی جهت رسیدن به بهترین راه‌های همکاری و موفقیت در پروژه‌های مورد علاقه و واجد منافع مشترک برای طرفین، همواره در ارتباط تنگاتنگ با مشتریان قرار دارد. خدمات مهندسی ارائه شده به مشتریان همواره یکی از اصول مهم شرکت کیمیارازی بوده است. &lt;/p&gt;
        ///&lt;p&gt;با تکیه بر تیم حرفه ای و ارتباط نزدیک با مشتریان، شرکت کیمیارازی ساپورت فنی و انتقال دانش لازم را جهت ارتقای سطح کیفی محصولات مشتریان فراهم می کند. ما جهت فراهم کردن بهترین راه حل‌ها تا رسیدن به بهترین نتایج متناسب با شرایط ویژه هر مشتری با آنها در ارتباط ن [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیمیارازی - خدمات.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات ارائه شده توسط واحد خدمات مهندسی شرکت کیمیارازی به شرکت‌های تولید کننده کاشی و سرامیک در دو بخش لعاب و جوهر دیجیتال ارائه می‌شوند..
        /// </summary>
        public static string Subhead {
            get {
                return ResourceManager.GetString("Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی و ساخت انواع لعاب مورد نظر شما.
        /// </summary>
        public static string Svc1h {
            get {
                return ResourceManager.GetString("Svc1h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما آمادگی داریم که هر گونه لعاب (فریت، مجموعه، پودر و…) را به طور اختصاصی مناسب شرایط تولید شما طراحی و روی خط تولید شما تست کنیم تا مناسب‌ترین فرمول ممکن جهت رسیدن به محصول نهایی با کیفیت دلخواه حاصل شود..
        /// </summary>
        public static string Svc1t {
            get {
                return ResourceManager.GetString("Svc1t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارائه مشاوره در خصوص رفع مشکلات و بهبود کیفیت محصولات شرکت‌های کاشی و سرامیک.
        /// </summary>
        public static string Svc2h {
            get {
                return ResourceManager.GetString("Svc2h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأمین کیفیت بالای تولیدات مشتریان از تعهدات کیمیارازی بوده و در این راه از طریق ارائه محصولات با کیفیت و نیز همراهی و همکاری در جهت رفع مشکلات تولید مشتری و توصیه به تغییرات مناسب در کنار مشتریان خود خواهد بود..
        /// </summary>
        public static string Svc2t {
            get {
                return ResourceManager.GetString("Svc2t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همراهی کارشناسان ما در انجام تست‌های آزمایشگاهی و صنعتی .
        /// </summary>
        public static string Svc3h {
            get {
                return ResourceManager.GetString("Svc3h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارشناسان مجرب شرکت آماده انجام تست‌های آزمایشگاهی و صنعتی لعاب‌های مورد استفاده کارخانجات کاشی هستند تا بتوانند بهترین کیفیت را به مشتریان ارائه نمایند..
        /// </summary>
        public static string Svc3t {
            get {
                return ResourceManager.GetString("Svc3t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطبیق طرح‌های مورد نظر شما با جوهرهای ما.
        /// </summary>
        public static string Svc4h {
            get {
                return ResourceManager.GetString("Svc4h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشتریانی که قبلاً طرح‌هایی با جوهرهای دیگر تولید کرده و وارد بازار کرده‌اند این امکان وجود دارد تا با کمک کارشناسان کیمیارازی طرح‌های قبلی را با جوهر کیمیارازی کاملاً منطبق با طرح و رنگ قبل تولید کرده و هیچ نگرانی از باب انطباق رنگ نداشته باشند..
        /// </summary>
        public static string Svc4t {
            get {
                return ResourceManager.GetString("Svc4t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساخت و اصلاح پروفایل.
        /// </summary>
        public static string Svc5h {
            get {
                return ResourceManager.GetString("Svc5h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیمیارازی بنا به درخواست مشتری با بهره‌گیری از دستگاه‌ها و نرم‌افزارهای روز دنیا قابلیت ساخت پروفایل متناسب با کلیه شرایط بدنه، انگوب، لعاب، پخت و… را در کوتاه‌ترین زمان دارد..
        /// </summary>
        public static string Svc5t {
            get {
                return ResourceManager.GetString("Svc5t", resourceCulture);
            }
        }
    }
}
