//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpecialGlazes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecialGlazes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.SpecialGlazes", typeof(SpecialGlazes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; در برخی موارد برای رسیدن به افکت‌های خاص در طرح‌ها٬ ناچار به استفاده از محصولات ویژه این افکت‌ها هستیم. با استفاده از این لعاب‌ها می‌توان طرح‌هایی را پیاده کرد که اجرای آنها بدون به کار بردن لعاب‌های ویژه امکان‌پذیر نیست.&lt;/p&gt;
        ///                &lt;p&gt; با استفاده از این مواد می‌توان افکت‌هایی مانند ایجاد برجستگی یا فرورفتگی، ایجاد جلای فلزی٬ طرح‌های ترک‌دار و ... روی سطح کاشی ایجاد کرد.&lt;/p&gt;
        ///                &lt;p&gt;
        ///                    لعاب‌های ویژه تولیدی شرکت کیمیارازی با فناوری و دستگاه‌های مدرن روز تولید شده  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لعاب‌های ویژه.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات - لعاب‌های ویژه.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod1Feature {
            get {
                return ResourceManager.GetString("Prod1Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لعاب پروتکشن.
        /// </summary>
        public static string Prod1H {
            get {
                return ResourceManager.GetString("Prod1H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لعاب‌های ویژه.
        /// </summary>
        public static string Prod1Subhead {
            get {
                return ResourceManager.GetString("Prod1Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod1Text {
            get {
                return ResourceManager.GetString("Prod1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod2Feature {
            get {
                return ResourceManager.GetString("Prod2Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لعاب متالیک.
        /// </summary>
        public static string Prod2H {
            get {
                return ResourceManager.GetString("Prod2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لعاب‌های ویژه.
        /// </summary>
        public static string Prod2Subhead {
            get {
                return ResourceManager.GetString("Prod2Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod2Text {
            get {
                return ResourceManager.GetString("Prod2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod3Feature {
            get {
                return ResourceManager.GetString("Prod3Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لعاب ترکدار.
        /// </summary>
        public static string Prod3H {
            get {
                return ResourceManager.GetString("Prod3H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لعاب‌های ویژه.
        /// </summary>
        public static string Prod3Subhead {
            get {
                return ResourceManager.GetString("Prod3Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod3Text {
            get {
                return ResourceManager.GetString("Prod3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Feature {
            get {
                return ResourceManager.GetString("Prod4Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4H {
            get {
                return ResourceManager.GetString("Prod4H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Subhead {
            get {
                return ResourceManager.GetString("Prod4Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Text {
            get {
                return ResourceManager.GetString("Prod4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Subhead {
            get {
                return ResourceManager.GetString("Subhead", resourceCulture);
            }
        }
    }
}
