//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ThirdFiring {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThirdFiring() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KimiaRazi.Resources.ThirdFiring", typeof(ThirdFiring).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; پخت سوم عبارتست از ایجاد دکور روی محصولات سرامیک و پخت مجدد آنها در دماهای پایین‌تر که به ما اجازه استفاده از مواد ویژه دکور، مانند لوستر، رنگین کمانی، فلزات گرانبها، دانه شکری و ... را می دهد. این مواد در دماهای بالایی که جهت پخت لعاب مورد استفاده قرار می گیرد دوام نخواهند آورد. محصول مورد استفاده بستگی به پروسه تولید مورد استفاده متفاوت خواهد بود. &lt;/p&gt;&lt;p&gt;وتروزاهای تولیدی شرکت کیمیارازی با فناوری و دستگاه‌های مدرن روز تولید شده و با توجه به این که توزیع اندازه ذرات و دانه بندی در این محصول بسیار مهم  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکور انواع سرامیک (پخت سوم).
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات - پخت سوم.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod1Feature {
            get {
                return ResourceManager.GetString("Prod1Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وتروزای ترانسپارنت.
        /// </summary>
        public static string Prod1H {
            get {
                return ResourceManager.GetString("Prod1H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وتروزا.
        /// </summary>
        public static string Prod1Subhead {
            get {
                return ResourceManager.GetString("Prod1Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod1Text {
            get {
                return ResourceManager.GetString("Prod1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod2Feature {
            get {
                return ResourceManager.GetString("Prod2Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وتروزای متالیک.
        /// </summary>
        public static string Prod2H {
            get {
                return ResourceManager.GetString("Prod2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وتروزا.
        /// </summary>
        public static string Prod2Subhead {
            get {
                return ResourceManager.GetString("Prod2Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod2Text {
            get {
                return ResourceManager.GetString("Prod2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod3Feature {
            get {
                return ResourceManager.GetString("Prod3Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod3H {
            get {
                return ResourceManager.GetString("Prod3H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod3Subhead {
            get {
                return ResourceManager.GetString("Prod3Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod3Text {
            get {
                return ResourceManager.GetString("Prod3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Feature {
            get {
                return ResourceManager.GetString("Prod4Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4H {
            get {
                return ResourceManager.GetString("Prod4H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Subhead {
            get {
                return ResourceManager.GetString("Prod4Subhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Prod4Text {
            get {
                return ResourceManager.GetString("Prod4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Subhead {
            get {
                return ResourceManager.GetString("Subhead", resourceCulture);
            }
        }
    }
}
